name: C# Build and Test

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
  
      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test

  publish-to-nuget:
    needs: build-and-test
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x

      - name: Move Doc to icecream\
        run: copy README.md icecream\ && copy LICENSE icecream\

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and pack
        run: dotnet pack -c Release

      - name: Publish to NuGet
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY_FOR_ICECREAM }}